spring.application.name=event-registration
server.port=8085

# Base de données H2 en mémoire
spring.datasource.url=jdbc:h2:mem:inscriptions
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

spring.thymeleaf.cache=false

# ===== Keycloak / OAuth2 =====
spring.security.oauth2.client.registration.keycloak.client-id=event-registration
spring.security.oauth2.client.registration.keycloak.client-secret=mIqRz1XcYouOEs8Byh8GErl53Huepyvmb3iXKNoEWt28kNHMI0RC44AHTWlq9zq7KeELQY9Syhth9A7ES9JBVy
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8180/realms/master
